### ISSUE TITLE
Can not get toket, please add manual

### ISSUE THREAD

**Issue by daddvok** [Toxblh/samsung-tv-control#11]
`Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/usr/lib/node_modules/node-red/node_modules/express/lib/response.js:771:10)
    at ServerResponse.contentType (/usr/lib/node_modules/node-red/node_modules/express/lib/response.js:599:15)
    at ServerResponse.send (/usr/lib/node_modules/node-red/node_modules/express/lib/response.js:145:14)
    at /home/pi/.node-red/node_modules/node-red-contrib-samsung-tv-mk/lib/keys.js:8:13
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at /usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:275:10)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:127:14)
    at /home/pi/.node-red/node_modules/node-red-contrib-samsung-tv-mk/lib/keys.js:9:9
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at /usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/usr/lib/node_modules/node-red/node_modules/express/lib/middleware/init.js:40:5)
`
I see this in log, please help me to get token
Samsung NU7090

**Comment by increddibelly** [comment]
is ip and mac set correctly? the wifi mac and ip are different from cable connection mac and ip, if you have setup both just pick one on the TV menu.
trigger the Get Token node; a permission dialog will appear on the TV. choose allow, and you'll receive a token in the debug tab of nodered.

**Comment by daddvok** [comment]
Yes, after switching to node-red-contrib-samsung-tv-control all works perfect.
