### ISSUE TITLE
I have TV 2018, QE65Q9FN. I can' get token key.

### ISSUE THREAD

**Issue by Toxblh** [Toxblh/samsung-tv-control#8]
I have TV 2018, QE65Q9FN. I can' get token key. Every time I must have to confirm on TV.
msg : Object
object
_msgid: "24da16ad.38601a"
topic: ""
What I doing wrong?

_Originally posted by @Hudoba in https://github.com/Toxblh/samsung-tv-control/issues/5#issuecomment-523178687_

**Comment by Toxblh** [comment]
Hey, @Hudoba could you send all log from ./example/index-dev.js

**Comment by Hudoba** [comment]
Hi Toxblh, where can I found this log file (./example/index-dev.js).  I use orange PI board.

**Comment by Toxblh** [comment]
@Hudoba this file https://github.com/Toxblh/samsung-tv-control/blob/master/example/index-dev.js

**Comment by Hudoba** [comment]
Hi, 
I was waiting my college to solve this problem, but unsuccessful Here is the log file. 

SyntaxError: Unexpected token *
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

**Comment by Toxblh** [comment]
okay, I recently update 2015-model branch and add `saveToken` option, it's can be useful for you
